Starting a Gradle Daemon (subsequent builds will be faster)

gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run-1785753856208.json
FAILURE: Build failed with an exception.


* What went wrong:
Configuring project with invalid directory
  Configuring project ':app' without an existing directory is not allowed. The configured projectDirectory '/home/runner/work/nfcmi/nfcmi/app' does not exist, can't be written to or is not a directory.
    For more information, please refer to https://docs.gradle.org/9.6.1/userguide/multi_project_builds.html#include_existing_projects_only.
    Possible solution: Make sure the project directory exists and is writable.

* Try:
> Run with --scan to get full insights from a Build Scan (powered by Develocity).

BUILD FAILED in 41s
[Incubating] Problems report is available at: file:///home/runner/work/nfcmi/nfcmi/build/reports/problems/problems-report.html
Error: Process completed with exit code 1.
